# Generated by Django 5.0 on 2025-12-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_order_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
